notifications:
    email: false

git:
    depth: 1

jobs:
    include:
    - stage: Course 1 (semester 1)
      language: c++
      compiler: g++
      env: FOLDER=course1/sem1 BUILD=cppBuild.sh
      install: skip
    - stage: Course 1 (semester 2)
      language: java
      jdk: openjdk11
      env: FOLDER=course1/sem2 BUILD=javaBuild.sh TEST=javaTest.sh
    - stage: Course 2 (semester 3)
      language: java
      jdk: openjdk11
      env: FOLDER=course2/sem3 BUILD=javaBuild.sh TEST=javaTest.sh
    - stage: Course 2 (semester 4)
      language: haskell
      compiler: ghc
      env: FOLDER=course2/sem4 BUILD=haskellBuild.sh
      install: skip

install:
    - sudo apt-get install maven

script:
    - ./scripts/searchScript.sh $FOLDER $BUILD $TEST
