notifications:
    email: false

git:
    depth: 1

jobs:
    include:
    - stage: Course 1 (semester 1)
      language: c++
      compiler: g++
      env: FOLDER=course1/sem1 BUILD=cppBuild.sh
    - stage: Course 1 (semester 2)
      language: java
      jdk: oraclejdk8
      env: FOLDER=course1/sem2 BUILD=javaBuild.sh TEST=javaTest.sh

script:
    - ./scripts/searchScript.sh $FOLDER $BUILD $TEST
