notifications:
    email: false

git:
    depth: 1

jobs:
    include:
    - stage: Course 1 (semester 1)
      language: c++
      compiler: g++
      env: FOLDER=course1/sem1 BUILD=cppBuild.sh
      install: skip
    - stage: Course 1 (semester 2)
      language: java
      jdk: oraclejdk8
      env: FOLDER=course1/sem2 BUILD=javaBuild.sh TEST=javaTest.sh

install:
    - wget https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.jar
    - wget https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar

script:
    - ./scripts/searchScript.sh $FOLDER $BUILD $TEST
