language: c++ java

env:
    - NAME="Course 1 (semester 1)"  FOLDER="course1/sem1" BUILD="cppBuild.sh"
    - NAME="Course 1 (semester 2)"  FOLDER="course1/sem2" BUILD="javaBuild.sh" TEST="javaTest.sh"

install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -y
    - sudo apt-get install -y g++-4.8
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50

script:
    - cd $FOLDER
    - ../../searchScript.sh "$NAME" $BUILD $TEST
    
notifications:
    email: false
